### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by AdamPengG** [realsenseai/realsense-ros#554]
I got the D435I camera. Then I install the sdk by "sudo apt-get install librealsense2-dev" and git clone the ROS wrapper.But the terminal shows a compilation error :
"/usr/include/c++/5/bits/stl_algo.h:162:34: error: no matching function for call to ‘__iterator_category(rs2::frameset::iterator&)’"
I have read the issue #547.Shall I reinstall the newest Realsense sdk or ROS wrapper.Another way ,maybe wait your new Ros wrapper.

**Comment by doronhi** [comment]
Fixed. Development branch should now work with librealsense 2.17.0 (latest release).
