### ISSUE TITLE
Expected timeframe for Jazzy support

### ISSUE THREAD

**Issue by KolinGuo** [realsenseai/realsense-ros#3108]
| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | D415 / D435 / D435i / L515                          | 
| Firmware Version                   | 5.16.0.1                          | 
| Operating System & Version |  Ubuntu 24.04 Noble Numbat | 
| Kernel Version (Linux Only)    | 6.8.0         | 
| Platform                                 | PC                |
| Librealsense SDK Version       |  N/A                                                    | 
| Language                               |  C++ / python        | 
| Segment			         |  Robot     | 
| ROS Distro			         |  Jazzy / Rolling    | 
| RealSense ROS Wrapper Version   |  N/A       | 

### Issue Description
Please don't view this as any form of pressure. I'm just curious about when can I expect `realsense-ros` (and `librealsense`) to add support for Ubuntu 24.04 and ROS 2 Jazzy? 

Thank you for your attention and greatly appreciate the efforts in maintaining `realsense-ros`!

**Comment by MartyG-RealSense** [comment]
Hi @KolinGuo  Thanks very much for your query.  I will highlight it to the RealSense ROS development team.

**Comment by Al-Kayd** [comment]
> Hi @KolinGuo Thanks very much for your query. I will highlight it to the RealSense ROS development team.

Would you happen to have any timeline on when it would be released for Ubuntu 24.04 Noble, ROS2 Jazzy, and Gazebo Sim 8 Harmonic?

Thank you.

**Comment by Nir-Az** [comment]
Hi @MohamedAlKayd ,
This work is planned, hopefully we can make it for the next release of LibRS + ROS.
Please keep track :)

**Comment by gregoryw3** [comment]
With the removal of L515 is the current suggestion to compile 2.54.2 (or 2.50.0) and corresponding ros wrapper for Ubuntu 24.04 (or other Jazzy supported distro) if you need L515? Or potentially is it possible to use a Docker container to use the old SDK, Wrappers, and Ubuntu, just for L515 while the host system can use the latest SDK and Drivers?

**Comment by MartyG-RealSense** [comment]
@gregoryw3  You should be able to use your L515 with an older Ubuntu version in a Docker container (such as 22.04) than the Ubuntu on the host, yes, with ROS2 wrapper 4.54.1.  At the time of writing this, the ROS2 wrapper currently supports Humble or Iron on Ubuntu 22.04.

For a ROS1 setup you should ideally use Ubuntu 18.04, ROS1 Noetic, SDK 2.50.0 or 2.51.1 and wrapper 2.3.2.

**Comment by MartyG-RealSense** [comment]
Does anyone require further assistance with this case, please?  Thanks!

**Comment by Al-Kayd** [comment]
> Hi @MohamedAlKayd , This work is planned, hopefully we can make it for the next release of LibRS + ROS. Please keep track :)

Thanks for replying, greatly appreciated. I am currently working on a project with the Camera and the versions I told you about, do you know when the next release  of LibRS + ROS would be?

**Comment by MartyG-RealSense** [comment]
Hi @MohamedAlKayd  Advance release dates for librealsense SDK or ROS wrapper updates are not provided.  In regard to librealsense, I recommend planning for a gap of roughly six months between releases.

New ROS wrapper releases usually do not occur until after a new librealsense version has been released.  However, the update model that the previous ROS wrapper 4.54.1 used was to apply regular updates to the source code version of the wrapper instead of waiting for the next librealsense release.  So installing the source code version of a wrapper instead of the package version should ensure that you have the latest updates.

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by Al-Kayd** [comment]
@MartyG-RealSense @Nir-Az 
Any updates regarding the wrapper for the D415 for ROS Jazzy? It has been 2 months.
Regards.

**Comment by MartyG-RealSense** [comment]
Hi @MohamedAlKayd  Earlier in this discussion at https://github.com/IntelRealSense/realsense-ros/issues/3108#issuecomment-2132114923 @Nir-Az stated that it is hoped that Jazzy support will be available in time for the next librealsense + ROS release.

2 weeks ago at https://github.com/IntelRealSense/librealsense/discussions/13072 it was further announced that the next release is planned for around the end of Q3 2024, which would be the end of September 2024.

**Comment by Nir-Az** [comment]
I can also update that initial version was already published for Jazzy
Please check and update :-)

**Comment by Al-Kayd** [comment]
@Nir-Az 
Thanks for the update, I was able to download it but it is not able to build. 

![image](https://github.com/user-attachments/assets/2913c57a-4e84-4879-9b18-4777add63e7a)

This is what I got when I downloaded it. I first try to build the realsense2_camera_msgs package and then the realsense2_camera package. I get a package issue when trying to build the first package.

Have you tested it with ros2 jazzy?

**Comment by Nir-Az** [comment]
> @Nir-Az Thanks for the update, I was able to download it but it is not able to build.
> 
> ![image](https://private-user-images.githubusercontent.com/96803939/352651850-2913c57a-4e84-4879-9b18-4777add63e7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNDkzMzcsIm5iZiI6MTcyMjE0OTAzNywicGF0aCI6Ii85NjgwMzkzOS8zNTI2NTE4NTAtMjkxM2M1N2EtNGU4NC00ODc5LTliMTgtNDc3N2FkZDYzZTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA2NDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MmVhZTljYjYxYjgzODI5MjgzNGUwY2IzMGFhMWE4ZjhiZTkyNTAwMmFjMmFkNjRhMWZiMzAwOGI2YmRmMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.973wHa9g1_9eIYtYfxW6ieIJ9CKusULO_OQxN4yhahk)
> 
> This is what I got when I downloaded it. I first try to build the realsense2_camera_msgs package and then the realsense2_camera package. I get a package issue when trying to build the first package.
> 
> Have you tested it with ros2 jazzy?

Are you building according to our manual using `colcon build` command?
Note that it is also available through Debain install on ROS Jazzy.

**Comment by Al-Kayd** [comment]
@Nir-Az 
Where is your manual? I am using Colcon Build but did it by myself.
Could you please provide the manual for colcon build and the Debian command? That would be greatly appreciated.
Regards.

**Comment by MartyG-RealSense** [comment]
Hi @MohamedAlKayd  You can find installation instructions for package build and colcon build by visiting the link below and clicking on **Step 3: Install Intel® RealSense™ ROS2 wrapper** to expand open the instructions.

https://github.com/IntelRealSense/realsense-ros?tab=readme-ov-file#installation-on-ubuntu

**Comment by Al-Kayd** [comment]
@Nir-Az @MartyG-RealSense 
Thank you, I was able to get it working. I wanted to get topics published from the realsense2 on Live feed, Face Recognition, Object Recognition, Depth Map, and Contour Map. Are there existing functions that I can use or would it have to be developed from scratch?

![image](https://github.com/user-attachments/assets/e3d1ffe5-160f-4dd7-bd99-eca8f4a8a0ad)

**Comment by MartyG-RealSense** [comment]
Typically you can find packages to add support in ROS for the functions that you need if they are not included by default in the RealSense ROS wrapper.

**Comment by Marco2929** [comment]
Does anyone have a working jazzy version for the L515?

**Comment by MartyG-RealSense** [comment]
Hi @Marco2929  Support for L515 officially ended after librealsense 2.50.0, whilst Jazzy support for Ubuntu 24.04 was first introduced in RealSense ROS wrapper 4.56.1 (which is designed for use with librealsense 2.56.1).  So it is unlikely that you will be able to achieve a librealsense / wrapper combination that can use an L515 with Jazzy, unfortunately.

**Comment by Marco2929** [comment]
But from your comments I understood it correct that at least humble was already support at that time right? So I'm maybe able to run the camera in a separate docker container

**Comment by MartyG-RealSense** [comment]
Humble support was first introduced in librealsense 2.51.1, which still had support unofficially for L515.  Wrapper 4.51.1 which is designed for use with 2.51.1 also supported L515.  So you could potentially use your L515 on Humble in a Docker container with librealsense 2.51.1 / wrapper 4.51.1.

**Comment by Marco2929** [comment]
Thanks a lot!

**Comment by Marco2929** [comment]
I set up the humble container but encountering the following error:

root@IPA-PC-327RFA5:/ws# ros2 launch realsense2_camera rs_launch.py depth_module.enable_auto_exposure:=false rgb_camera.enable_auto_exposure:=false align_depth.enable:=true
[INFO] [launch]: All log files can be found below /root/.ros/log/2025-12-11-10-22-59-892981-IPA-PC-327RFA5-220
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [realsense2_camera_node-1]: process started with pid [221]
[realsense2_camera_node-1] 
[realsense2_camera_node-1] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[realsense2_camera_node-1] This error state is being overwritten:
[realsense2_camera_node-1] 
[realsense2_camera_node-1]   'string data is not null-terminated, at ./src/serdata.cpp:384'
[realsense2_camera_node-1] 
[realsense2_camera_node-1] with this new error message:
[realsense2_camera_node-1] 
[realsense2_camera_node-1]   'invalid data size, at ./src/serdata.cpp:384'
[realsense2_camera_node-1] 
[realsense2_camera_node-1] rcutils_reset_error() should be called after error handling to avoid this.
[realsense2_camera_node-1] <<<
[realsense2_camera_node-1] [INFO] [1765448579.957074889] [camera.camera]: RealSense ROS v4.51.1
[realsense2_camera_node-1] [INFO] [1765448579.957112104] [camera.camera]: Built with LibRealSense v2.54.2
[realsense2_camera_node-1] [INFO] [1765448579.957117971] [camera.camera]: Running with LibRealSense v2.54.2
[realsense2_camera_node-1] [INFO] [1765448580.025464007] [camera.camera]: Device with serial number f1421872 was found.
[realsense2_camera_node-1] 
[realsense2_camera_node-1] [INFO] [1765448580.025591228] [camera.camera]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.0/video4linux/video0 was found.
[realsense2_camera_node-1] [INFO] [1765448580.025618584] [camera.camera]: Device with name Intel RealSense L515 was found.
[realsense2_camera_node-1] [INFO] [1765448580.025976134] [camera.camera]: Device with port number 2-1 was found.
[realsense2_camera_node-1] [INFO] [1765448580.026002581] [camera.camera]: Device USB type: 3.2
[realsense2_camera_node-1] [INFO] [1765448580.029398155] [camera.camera]: getParameters...
[realsense2_camera_node-1] [INFO] [1765448580.029954092] [camera.camera]: JSON file is not provided
[realsense2_camera_node-1] [INFO] [1765448580.029989714] [camera.camera]: Device Name: Intel RealSense L515
[realsense2_camera_node-1] [INFO] [1765448580.030011438] [camera.camera]: Device Serial No: f1421872
[realsense2_camera_node-1] [INFO] [1765448580.030033395] [camera.camera]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.0/video4linux/video0
[realsense2_camera_node-1] [INFO] [1765448580.030056615] [camera.camera]: Device FW version: 1.5.4.1
[realsense2_camera_node-1] [INFO] [1765448580.030107618] [camera.camera]: Device Product ID: 0x0B64
[realsense2_camera_node-1] [INFO] [1765448580.030130039] [camera.camera]: Sync Mode: Off
[realsense2_camera_node-1] [INFO] [1765448580.041251544] [camera.camera]: Set ROS param depth_module.profile to default: 640x480x30
[realsense2_camera_node-1] [INFO] [1765448580.045481772] [camera.camera]: Set ROS param rgb_camera.profile to default: 1280x720x30
[realsense2_camera_node-1] [INFO] [1765448580.045891318] [camera.camera]: Set ROS param gyro_fps to default: 100
[realsense2_camera_node-1] [INFO] [1765448580.045986909] [camera.camera]: Set ROS param accel_fps to default: 200
[realsense2_camera_node-1] [WARN] [1765448580.056621675] [camera.camera]: Could not set param: pointcloud.stream_index_filter with -1 Range: [-1, -2147483648]: parameter 'pointcloud.stream_index_filter' could not be set: Parameter {pointcloud.stream_index_filter} doesn't comply with integer range.
[realsense2_camera_node-1] [INFO] [1765448580.056991399] [camera.camera]: Stopping Sensor: L500 Depth Sensor
[realsense2_camera_node-1] [INFO] [1765448580.066207283] [camera.camera]: Starting Sensor: L500 Depth Sensor
[realsense2_camera_node-1] [INFO] [1765448580.088864115] [camera.camera]: Open profile: stream_type: Confidence(0), Format: RAW8, Width: 640, Height: 480, FPS: 30
[realsense2_camera_node-1] [INFO] [1765448580.088991016] [camera.camera]: Open profile: stream_type: Infra(0), Format: Y8, Width: 640, Height: 480, FPS: 30
[realsense2_camera_node-1] [INFO] [1765448580.089035931] [camera.camera]: Open profile: stream_type: Depth(0), Format: Z16, Width: 640, Height: 480, FPS: 30
[realsense2_camera_node-1] [INFO] [1765448580.089362628] [camera.camera]: Stopping Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1765448580.231661641] [camera.camera]: Starting Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1765448580.238726377] [camera.camera]: Open profile: stream_type: Color(0), Format: RGB8, Width: 1280, Height: 720, FPS: 30
[realsense2_camera_node-1] [INFO] [1765448580.239432309] [camera.camera]: RealSense Node Is Up!
[realsense2_camera_node-1] [WARN] [1765448580.374271719] [camera.camera]: 
[realsense2_camera_node-1] [WARN] [1765448580.374410593] [camera.camera]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.

The topics are available, and the images of depth and color are visible in RViz via the Jazzy container, but they cannot be synchronized by time, and the depth image is not subscribable as a topic command. I am aware that this is officially no longer supported, but I am very interested in whether you think this is solvable. It seems that there is a problem with rmw_cyclonedds_cpp. With 4.51.1 ist wasn't buildable due to:

261.5 /ws/src/librealsense-2.51.1/src/libusb/libusb.h:10:82: error: extended character ’ is not valid in an identifier
261.5 /ws/src/librealsense-2.51.1/src/libusb/libusb.h:13:82: error: extended character ‘ is not valid in an identifier
261.5    13 | /usr/include/libusb-1.0/libusb.h:767:4: warning: ISO C++ forbids zero-size array ‘dev_capability’ [-Wpedantic]
261.5       |                                                                                  ^
261.5 /ws/src/librealsense-2.51.1/src/libusb/libusb.h:13:82: error: extended character ’ is not valid in an identifier
261.5 /ws/src/librealsense-2.51.1/src/libusb/libusb.h:18:83: error: extended character ‘ is not valid in an identifier
261.5    18 | /usr/include/libusb-1.0/libusb.h:1260:4: warning: ISO C++ forbids zero-size array ‘iso_packet_desc’ [-Wpedantic]

But it worked with 4.54.1, that's also what I found in some repos on github

System/Setup:

- ROS2 Humble Container

- RealSense L515

- realsense2_camera v4.54.1

- librealsense2 v2.54.2

- RMW: rmw_cyclonedds_cpp

**Comment by MartyG-RealSense** [comment]
I note that your L515's firmware driver version is 1.5.4.1 which is very old and was designed for use with librealsense 2.42.1.  For librealsense 2.54.2, the final L515 firmware version - **1.5.8.1** - is recommended.  As you have a mostly working setup with 2.54.2 / 4.54.1 it may not be necessary to update the firmware though.

If you add the parameter **enable_sync:=true**  to your launch instruction then the wrapper should gather the closest frames of different sensors (infrared, color and depth) to be sent with the same timetag.

The launch may be using the HARDWARE_CLOCK domain because on the L515 camera model, Global Time is disabled by default.  ROS has its own built-in time correction mechanism though which means that it may not be necessary to have Global Time enabled.  You could try adding **global_time_enabled:=true** to your launch instruction though to enable it.

**Comment by LiPengfei0805** [comment]
Hi @MartyG-RealSense ，I am using a D455 camera with ROS 2 Jazzy. I am encountering an issue where the FPS of both the color and depth topics is lower than the expected 30 FPS and is unstable.
**Hardware & OS:**
    Onboard computer: RK3588
    OS: Ubuntu 24.04 (Linux lubancat 6.1.84 #1 SMP Mon Mar 3 11:01:38 CST 2025 aarch64 aarch64 aarch64 GNU/Linux)
**Software versions tested:**
    librealsense SDK: v2.56.1 (also tested v2.57.1 and v2.56.4)
    realsense-ros: 4.56.1 (also tested 4.57.6 and other corresponding versions)
I launch the camera node with the following command:
`ros2 launch realsense2_camera rs_launch.py depth_module.depth_profile:=640x480x30 rgb_camera.color_profile:=640x480x30 enable_gyro:=false enable_accel:=false`
Then I check the FPS using: `ros2 topic hz /camera/camera/color/image_raw` .
The result is always below 30 FPS and unstable:
ros2 topic hz /camera/camera/color/image_raw
average rate: 19.952
	min: 0.032s max: 0.233s std dev: 0.04673s window: 22
average rate: 19.699
	min: 0.030s max: 0.300s std dev: 0.05409s window: 42
average rate: 17.686
	min: 0.030s max: 0.334s std dev: 0.06110s window: 56
average rate: 17.844
	min: 0.030s max: 0.334s std dev: 0.05961s window: 75
average rate: 16.755
	min: 0.030s max: 0.598s std dev: 0.07967s window: 90
average rate: 18.361
	min: 0.030s max: 0.598s std dev: 0.07070s window: 117
average rate: 16.269
	min: 0.030s max: 0.603s std dev: 0.09021s window: 120
average rate: 15.158
	min: 0.030s max: 0.667s std dev: 0.10354s window: 131
average rate: 14.827
	min: 0.030s max: 0.667s std dev: 0.10617s window: 143
average rate: 15.030
	min: 0.030s max: 0.667s std dev: 0.10113s window: 160
average rate: 15.756
	min: 0.030s max: 0.667s std dev: 0.09543s window: 184
average rate: 16.719
	min: 0.030s max: 0.667s std dev: 0.08952s window: 212
average rate: 17.687
	min: 0.030s max: 0.667s std dev: 0.08424s window: 242
average rate: 18.336
	min: 0.030s max: 0.667s std dev: 0.08000s window: 271
Even if I disable either the color or depth stream (by setting enable_color:=false or enable_depth:=false), the problem still exists.
However, When I use the official realsense-viewer, the camera maintains a stable 30 FPS with the higher resolution of 848×480@30 profile, so I think the problem is caused by ros2, and my co-worker ran `export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp` to switch the DDS implementation. After this change, the topic hz stabilizes at around 27 Hz, but it is still lower than the expected 30 Hz. 
I have no further ideas on how to resolve this. Could you please help figure out the cause?
Furthermore, last summer I used the exact same onboard computer (RK3588) with **ROS1 Noetic** to run the D455, and I did not experience this problem at all (stable 30 FPS in rostopic).

**Comment by MartyG-RealSense** [comment]
Hi @LiPengfei0805  I have had reports from RealSense ROS users that CycloneDDS provides improved performance, as your co-worker said.

Please try inputting the command below during runtime after launch has completed.

`ros2 param set /camera/camera rgb_camera.auto_exposure_priority false`

When auto-exposure is enabled and the RGB option **auto_exposure_priority** is disabled, it can force the depth and color FPS to maintain a constant rate instead of being permitted to vary.

**Comment by LiPengfei0805** [comment]
Thank you @MartyG-RealSense,
I tried the command `ros2 param set /camera/camera rgb_camera.auto_exposure_priority false` after launching the camera node.
At the beginning, the FPS improved, but after a short while it gradually decreased again and eventually stabilized around 27 Hz (typically fluctuating between 26–28 Hz).
It seems this parameter helps a little at first but is not sufficient to maintain a stable 30 Hz.
Is there anything else I can try to resolve this issue and achieve a consistent 30 FPS?
Thanks again!

**Comment by MartyG-RealSense** [comment]
Let's next try disabling auto-exposure so that a fixed exposure value is used, in order to eliminate the possibility that automatic exposure value changes are causing the FPS to drop (as there is a relationship between exposure value and FPS that can cause FPS to reduce or increase).

`ros2 param set /camera/camera depth_module.enable_auto_exposure false`

**Comment by LiPengfei0805** [comment]
Thank you @MartyG-RealSense for your previous suggestions.
I also tried the command `ros2 param set /camera/camera depth_module.enable_auto_exposure false`
Unfortunately, it didn't help — the FPS still stabilized around 27 Hz (typically 26–28 Hz), just like before.
Additionally, on a more powerful x86 computer (running the same Ubuntu 24.04 + ROS 2 Jazzy, and the same versions of SDK and realsense-ros), I get a stable 30 Hz on both streams — even without switching to CycloneDDS. This shows the issue doesn't appear on x86 hardware.
It seems the current combination of librealsense + realsense-ros on ROS 2 Jazzy may not run optimally on the RK3588 platform right now.
I will give up running D455 on rk3588 temporarily. I hope this gets improved in a future update so that stable 30 FPS becomes possible on this hardware.
Thanks again for your help!

**Comment by MartyG-RealSense** [comment]
You are very welcome, @LiPengfei0805
